In [1]:
import torch
print(torch.__version__)

2.0.1+cu118


# Introduction to Tensors

## Creating Tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get tensor back as python int
scalar.item()

7

In [5]:
#Vector (has more than one number)
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [38]:
# TENSOR
TENSOR = torch.tensor([[[[1, 2, 3, 5],
                         [3, 6, 9, 6],
                         [2, 4, 5, 2],
                         [1, 2, 4, 6]]]])
TENSOR

tensor([[[[1, 2, 3, 5],
          [3, 6, 9, 6],
          [2, 4, 5, 2],
          [1, 2, 4, 6]]]])

In [39]:
TENSOR.ndim

4

In [40]:
TENSOR.shape

torch.Size([1, 1, 4, 4])

In [45]:
TENSOR[0]

tensor([[[1, 2, 3, 5],
         [3, 6, 9, 6],
         [2, 4, 5, 2],
         [1, 2, 4, 6]]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> Update random numbers -< Look at data -> Update random Numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [102]:
### Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.shape

(tensor([[0.8409, 0.0812, 0.1151, 0.5222],
         [0.7764, 0.1557, 0.2927, 0.8260],
         [0.5095, 0.9087, 0.4450, 0.5005]]),
 torch.Size([3, 4]))

In [76]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #Height , width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [81]:
torch.rand(size=(3, 3))

tensor([[0.1041, 0.3048, 0.9165],
        [0.6676, 0.5184, 0.7995],
        [0.5791, 0.8404, 0.9607]])

Zeros and ones

In [104]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [106]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [107]:
ones.dtype

torch.float32

In [108]:
random_tensor.dtype

torch.float32

# Creating a range of tensors and tensors-like

In [124]:
# Use torch.arrange

one_to_ten = torch.arange(start=1, end=16, step= 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [125]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input=one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

Default is float32

In [126]:
# Float 32 Tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g. float32 or float16, float64)
                               device= None, # What device is your tensor on
                               requires_grad=False) # Whether or not to track gradiants

float_32_tensor

tensor([3., 6., 9.])

In [127]:
float_32_tensor.dtype

torch.float32

In [128]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [137]:
float_16_tensor * float_32_tensor

tensor([1., 1., 1.])

In [148]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [149]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

1. Tensors not right datatype - To get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - To get shape from a tensor, can use `tensor.shape`
3. Tensors not on right device - To get device from a tensor `tensor.device`

In [155]:
#Create a tensor
some_tensor = torch.rand(3, 4, dtype= torch.float16)
some_tensor

tensor([[0.8262, 0.1025, 0.3496, 0.6646],
        [0.7026, 0.8862, 0.7168, 0.3887],
        [0.5986, 0.9814, 0.9556, 0.8618]], dtype=torch.float16)

In [156]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.8262, 0.1025, 0.3496, 0.6646],
        [0.7026, 0.8862, 0.7168, 0.3887],
        [0.5986, 0.9814, 0.9556, 0.8618]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication


In [168]:
# Create a tensor Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [169]:
tensor * 10

tensor([10, 20, 30])

In [170]:
tensor

tensor([1, 2, 3])

In [171]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [172]:
# Try out PyTorch built-in functions

torch.mul(tensor, 10)



tensor([10, 20, 30])